/**
 * Generate a BIP-39 mnemonic + 4 accounts derived from it for Pulse e2e
 * testing on Base Sepolia. The seed phrase imports cleanly into MetaMask
 * so you only do one wallet import — the 4 derived accounts (account 0–3)
 * appear automatically.
 *
 * Roles by derivation path (m/44'/60'/0'/0/N):
 *   N=0  DEPLOYER         deploys Pulse + hook + test tokens     (~1.0 ETH)
 *   N=1  AGENT            calls Pulse.commit; ERC-8004 principal (~0.30 ETH)
 *   N=2  WATCHER          calls Pulse.reveal directly             (~0.05 ETH)
 *   N=3  DEMO_TEE_SIGNER  signs sealed reasoning off-chain        (0 ETH)
 *
 * Keys are written to:
 *   ./.env                    (consumed by forge scripts + SDK)
 *   ./hermes-sandbox/.env     (consumed by Hermes container)
 *
 * The user funds addresses; the script never touches funds.
 *
 * Run: bun run scripts/gen-keys.ts
 */

import {generateMnemonic, mnemonicToAccount, english} from "viem/accounts";
import {existsSync, readFileSync, writeFileSync} from "node:fs";
import {dirname, resolve} from "node:path";
import {fileURLToPath} from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

// 256-bit entropy → 24-word phrase. Override-safe: if MNEMONIC_OVERRIDE is
// set in env, reuse it instead of generating a new one (so re-running this
// script doesn't regenerate keys you've already funded).
const mnemonic = process.env.MNEMONIC_OVERRIDE || generateMnemonic(english, 256);

interface Key {
    role: string;
    derivationPath: string;
    privateKey: `0x${string}`;
    address: `0x${string}`;
    fundingTarget: string;
    notes: string;
}

const roles = [
    {role: "DEPLOYER", fundingTarget: "1.0 ETH", notes: "Deploys Pulse + hook + mock tokens"},
    {role: "AGENT", fundingTarget: "0.30 ETH", notes: "Calls Pulse.commit; ERC-8004 principal"},
    {role: "WATCHER", fundingTarget: "0.05 ETH", notes: "Closes atomic-rollback via direct reveal"},
    {role: "DEMO_TEE_SIGNER", fundingTarget: "0 ETH", notes: "Signs sealed reasoning only — never send funds"}
];

const keys: Key[] = roles.map(({role, fundingTarget, notes}, i) => {
    const account = mnemonicToAccount(mnemonic, {accountIndex: 0, addressIndex: i});
    return {
        role,
        derivationPath: `m/44'/60'/0'/0/${i}`,
        privateKey: account.getHdKey().privateKey
            ? (`0x${Buffer.from(account.getHdKey().privateKey!).toString("hex")}` as `0x${string}`)
            : (() => {
                  // viem's mnemonicToAccount returns an HDAccount; if privateKey isn't directly
                  // exposed we fall back to deriving via a different path
                  throw new Error("mnemonicToAccount didn't expose privateKey — viem version mismatch");
              })(),
        address: account.address,
        fundingTarget,
        notes
    };
});

const envBlock = `# ── Generated by scripts/gen-keys.ts on ${new Date().toISOString()} ────
# Throwaway BIP-39 testnet keys for Base Sepolia e2e. DO NOT COMMIT.
# Never reuse on mainnet — these keys exist in chat history + .env files.

# Mnemonic (import into MetaMask once; all 4 accounts derive from it).
# Stored here for redundancy — if you lose this you regenerate by re-running
# scripts/gen-keys.ts. To preserve across reruns, set MNEMONIC_OVERRIDE.
MNEMONIC="${mnemonic}"

# Account 0 — Deployer (m/44'/60'/0'/0/0) — ~1.0 ETH on Base Sepolia
DEPLOYER_KEY=${keys[0].privateKey}
# Address: ${keys[0].address}

# Account 1 — Agent (m/44'/60'/0'/0/1) — ~0.30 ETH on Base Sepolia
AGENT_PRIVATE_KEY=${keys[1].privateKey}
# Address: ${keys[1].address}

# Account 2 — Watcher (m/44'/60'/0'/0/2) — ~0.05 ETH on Base Sepolia
WATCHER_KEY=${keys[2].privateKey}
# Address: ${keys[2].address}

# Account 3 — Demo TEE signer (m/44'/60'/0'/0/3) — NEVER fund (0 ETH)
DEMO_TEE_SIGNER_KEY=${keys[3].privateKey}
# Address: ${keys[3].address}

# ── RPC + chain ───────────────────────────────────────────────────────────
BASE_SEPOLIA_RPC_URL=https://sepolia.base.org

# ── Canonical ERC-8004 (do not redeploy) ──────────────────────────────────
IDENTITY_REGISTRY=0x8004A818BFB912233c491871b3d84c89A494BD9e
REPUTATION_REGISTRY=0x8004B663056A597Dffe9eCcC1965A193B7388713

# ── Filled in after Day 1 deploy ──────────────────────────────────────────
PULSE_ADDRESS=
HOOK_ADDRESS=
POOL_MANAGER=
AGENT_ID=
AGENT_ENS_NAME=

# ── External services ─────────────────────────────────────────────────────
UNISWAP_TRADING_API_KEY=-m9xHsMAHawxXJpxfDiohec0zZI5xNc8x3GfEFVYQ1s
ZG_API_KEY=
ZG_BROKER_URL=
ZG_SIGNER_ADDRESS=
ZG_MODEL=deepseek-reasoner
`;

const rootEnvPath = resolve(repoRoot, ".env");
writeFileSync(rootEnvPath, envBlock, {mode: 0o600});

const sandboxEnvPath = resolve(repoRoot, "hermes-sandbox/.env");
writeFileSync(sandboxEnvPath, envBlock, {mode: 0o600});

// Also write the mnemonic to a separate sentinel file so the user can quickly
// pull it for MetaMask import without scrolling through a multi-key .env.
const mnemonicPath = resolve(repoRoot, "MNEMONIC.txt");
writeFileSync(
    mnemonicPath,
    `# Throwaway BIP-39 mnemonic for Base Sepolia testing. DO NOT COMMIT. DO NOT REUSE.\n${mnemonic}\n`,
    {mode: 0o600}
);

console.log("✓ Wrote .env files (mode 0600):");
console.log(`  ${rootEnvPath}`);
console.log(`  ${sandboxEnvPath}`);
console.log(`✓ Wrote ${mnemonicPath} (gitignored — quick MetaMask import reference)`);
console.log();
console.log("─── Mnemonic (24 words) ─────────────────────────────────────────────────");
console.log();
console.log("  " + mnemonic);
console.log();
console.log("─── Addresses (derived from above) ──────────────────────────────────────");
for (const k of keys) {
    console.log(`  ${k.role.padEnd(18)}  ${k.address}   ← ${k.fundingTarget}`);
    console.log(`  ${" ".repeat(18)}  ${k.derivationPath}   (${k.notes})`);
}
console.log();
console.log("─── Next steps ──────────────────────────────────────────────────────────");
console.log();
console.log("  1. MetaMask → Import wallet → paste the 24 words above");
console.log("     The first 4 accounts MetaMask shows are the ones above.");
console.log();
console.log("  2. Add Base Sepolia network in MetaMask:");
console.log("     Network: Base Sepolia");
console.log("     RPC:     https://sepolia.base.org");
console.log("     Chain:   84532");
console.log("     Symbol:  ETH");
console.log("     Explorer: https://sepolia.basescan.org");
console.log();
console.log("  3. Fund accounts 0, 1, 2 from a Base Sepolia faucet:");
console.log("     https://portal.cdp.coinbase.com/products/faucet  (most reliable)");
console.log("     https://www.alchemy.com/faucets/base-sepolia");
console.log("     https://www.superchain.eco/faucets");
console.log();
console.log("     Total needed: ~1.35 ETH");
console.log("     DO NOT fund account 3 (TEE signer — signing only).");
console.log();
console.log("  4. To preserve these exact keys across re-runs of this script:");
console.log("     export MNEMONIC_OVERRIDE=\"$(cat MNEMONIC.txt | tail -1)\"");
